version: "3.8"

services:

  mariadb:
    image: my-peozzle-mariadb:v1
    container_name: my-peozzle-mariadb
    ports:
      - "3306:3306"
    environment:
      - MARIADB_DATABASE=bitnami_wordpress
      - MARIADB_ROOT_PASSWORD=secretroot
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=797ea7712224fe28342488a59cfe715722e2a021563127e3609afd7becfc274a
    volumes:
      - my_peozzle_mariadb_data:/bitnami/mariadb
    networks:
      - peozzle_network

  wordpress:
    image: my-peozzle-wordpress:v1
    container_name: my-peozzle-wordpress-container
    depends_on:
      - mariadb # service name
    ports:
      - "80:8080"
    environment:
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=797ea7712224fe28342488a59cfe715722e2a021563127e3609afd7becfc274a
      - WORDPRESS_USERNAME=admin
      - WORDPRESS_PASSWORD=AAuaaaale0!
      - WORDPRESS_EMAIL=gowtham@peozzle.com
      - WORDPRESS_BLOG_NAME=Peozzle
      - WORDPRESS_MULTISITE_EXTERNAL_HTTP_PORT_NUMBER=80
      - WORDPRESS_ENABLE_MULTISITE=yes
      - WORDPRESS_MULTISITE_NETWORK_TYPE=subdomain
      - WORDPRESS_MULTISITE_HOST=peozzle.local

      - WORDPRESS_SCHEME=http

      - APACHE_HTTP_PORT_NUMBER=8080
      - WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=yes

    volumes:
      - my_peozzle_wordpress_data:/bitnami/wordpress
    networks:
      - peozzle_network

volumes:
  my_peozzle_wordpress_data:
  my_peozzle_mariadb_data:

networks:
  peozzle_network:
    driver: bridge